#!/usr/bin/env python

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm
from scipy import constants
import argparse
import sys
from scipy.stats import gaussian_kde

# return magnetic field given P and Pdot
# bk is the constant in the B field equation
bk = 19.505
bk10 = np.power(10.,bk)
def bsurf(p0,p1):
    bsurf = np.sqrt(np.multiply(p0,p1)) * bk10
    return bsurf

# return log age in years given P and Pdot
def age(p0,p1):
    age = np.log10(p0/2.0/p1/secondsPerYear)
    return age

# return log edot given P and Pdot
def edot(p0,p1):
    edot = 45.0 + np.log10((4.0*np.pi*np.pi*p1)/(np.power(p0,3)))
    return edot

# Deathline test
# Is the edot less than 10^30 ? If so then the pulsar has crossed the death line
def deathlinetest(p0,p1):
    return edot(p0,p1) < 30.0

# Luminosity test
# The luminosity is the sqrt(Edot) - above Edot_highest all pulsars are detected
# returns true if detected
def luminositytest(p0,p1,random_number):
    L_edot = np.power(10, 0.5 * (edot (p0,p1) - Edot_highest))
    return L_edot < random_number

# the dither update function
def dither_update(psr_array):
# update p0:  p0 = p1 * timestep
    psr_array[:,0] += psr_array[:,1] * stepSec

# update p1, change braking index only in user-defined multiples of birthrate
# new p1 = B^2 / P0 * dither
    if np.mod(time, stepsize * birthrate) == 0:
        braking_sigma = 5. / (np.sqrt(time))
        psr_array[:,7] = braking_sigma * np.random.randn(current_pulsars) + 1.0
    psr_array[:,1] = np.power(psr_array[:,2],2)/np.power(bk10,2)/psr_array[:,0] * np.abs(psr_array[:,7])

# update magnetic field
    psr_array[:,2] = bsurf(psr_array[:,0],psr_array[:,1])

# update alpha by dividing through by the alpha_update constant
    psr_array[:,3] = psr_array[:,3]/alpha_update
    return psr_array
# end of update function

# generate the pulsar array
# the array has the following columns
# 0: period 
# 1: period derivative 
# 2: magnetic field 
# 3: alpha
# 4: zeta
# 5: index number
# 6: luminosity cutoff
# 7: braking noise
def generatePSRs(npsr, muP0, muP1, sigmaP0, sigmaP1):
    p0_array = np.power(10.,np.random.normal(np.log10(muP0), sigmaP0, npsr))
    p1_array = np.power(10.,np.random.normal(muP1, sigmaP1, npsr))
    this_bsurf = bsurf(p0_array, p1_array)
    this_a = np.arccos(np.random.uniform(0.0, 1.0, npsr))
    this_zeta = np.arccos(np.random.uniform(0.0, 1.0, npsr))
    this_index = np.arange(npsr)
    this_lmin = np.random.uniform(0.0, 1.0, npsr)
    braking_noise = np.full(npsrs, 1.0)

    p0p1baz = np.column_stack((p0_array, p1_array, this_bsurf, this_a, this_zeta, this_index, this_lmin, braking_noise))
    return p0p1baz

# Parse arguments
parser = argparse.ArgumentParser(description='Evolve pulsars on the P-Pdot diagram')
parser.add_argument('-alpha', metavar="<alpha>", type=float, default='45', help='inclination angle in degrees (default = 45)')
parser.add_argument('-p0', metavar="<p0>", type=float, default='0.020', help='period in s (default = 0.02 s)')
parser.add_argument('-p1', metavar="<p1>", type=float, default='-12.0', help='log p-dot in s/s (default = -12 )')
parser.add_argument('-edotmax', metavar="<edotmax>", type=float, default='34.0', help='log of max edot detected (default = 34 )')
parser.add_argument('-s0', metavar="<s0>", type=float, default='0.0001', help='log sigma of p0 distribution (default = 0.0001)')
parser.add_argument('-s1', metavar="<s1>", type=float, default='0.0001', help='log sigma of p1 (default = 0.0001 )')
parser.add_argument('-maxage', metavar="<maxage>", type=float, default='8', help='log max age in years (default = 8 )')
parser.add_argument('-birthrate', metavar="<birthrate>", type=float, default='100', help='birth rate in years (default = 100 )')
parser.add_argument('-stepsize', metavar="<stepsize>", type=float, default='1', help='update step in units of birthrate (default = 1 )')
parser.add_argument('-npsr', metavar="<npsr>", type=int, default='100000', help='total number of pulsars to generate (default = 100000 )')
parser.add_argument('-iseed', metavar="<iseed>", type=int, default='4', help='integer seed for a pseudo-random number generator (default = 4)')
parser.add_argument('-file', metavar="<file>", default='ppdot.dat', help='ppdot file (default = psr.list)')

args = parser.parse_args()
alpha = args.alpha
p0_0 = args.p0
p1_0 = args.p1
s0_0 = args.s0
s1_0 = args.s1
maxage = args.maxage
birthrate = args.birthrate
stepsize = args.stepsize
npsrs = args.npsr
iseed = args.iseed
file = args.file
Edot_highest = args.edotmax

# the observed p-pdot diagram read in from file generated by psrcat and plotted
ppdot_diagram = np.loadtxt(file)
known_pulsars = ppdot_diagram.shape[0]
x = np.zeros(known_pulsars)
y = np.zeros(known_pulsars)
for i in range(known_pulsars):
    x[i] = np.log10(ppdot_diagram[i,0])
    y[i] = np.log10(ppdot_diagram[i,1])
xy = np.vstack([x,y])
z = gaussian_kde(xy)(xy)
fig, ax = plt.subplots()
ax.scatter(x, y, c=z, s=10, edgecolor='')

# em_height is the emission height in km
# alpha_decay is the alpha decay time in years
# alpha update is the fractional change in alpha per birthrate
secondsPerYear = 365.25*86400.0
lightspeed = 299792.0
em_height = 300.0
alpha_decay = np.power(10.,7) 
alpha_update = np.exp(birthrate / alpha_decay)

stepSec = birthrate * secondsPerYear
psr_array = generatePSRs(npsrs, p0_0, p1_0, s0_0, s1_0)
observed_pulsars = np.zeros(psr_array.shape)
current_pulsars = npsrs
total_steps = npsrs

dead_pulsars = 0
detected = 0
tot_dead_pulsars = 0
not_beaming = 0
death_liners = 0
weaks = 0
time = 0
# START MAIN LOOP
for i in range(total_steps):
    print "Loop info: ", i, "killed: ", tot_dead_pulsars," remaining: ", current_pulsars, "detected: ", detected, "time: ", time
    time = (i+1) * birthrate
    tot_dead_pulsars = 0

    psr_array = dither_update(psr_array)
# rho is the cone opening angle = 3 * sqrt (pi/2 * height / P0 / c)
# beta = abs(zeta - alpha) - absolute value to check for +/- rho
    rho = 3.0 * np.sqrt(np.pi * em_height / 2.0 / psr_array[:,0] / lightspeed)
    beta = np.abs(psr_array[:,4] - psr_array[:,3])

# Check which pulsars are already not beaming towards you
# this is the case if beta > rho
    dead_pulsars = 0
    dead_index = []
    for j in range(current_pulsars):
        if beta[j] > rho[j]:
            dead_pulsars +=1
            not_beaming +=1
            dead_index.append(j)
# delete these pulsars from the array
    psr_array = np.delete(psr_array,dead_index,0)
    current_pulsars -= dead_pulsars
    tot_dead_pulsars += dead_pulsars

# Scythe through the array looking for pulsars below the death or under-luminous
    dead_pulsars = 0
    dead_index = []
    if np.mod(time, 10000) == 0:
        for j in range(current_pulsars):
# death line test
            if deathlinetest(psr_array[j,0],psr_array[j,1]):
                dead_index.append(j)
                dead_pulsars +=1
                death_liners +=1
# luminosity test          
            elif luminositytest(psr_array[j,0],psr_array[j,1],psr_array[j,6]):
                dead_index.append(j)
                dead_pulsars +=1
                weaks +=1
# delete these pulsars from the array
        psr_array = np.delete(psr_array,dead_index,0)
        current_pulsars -= dead_pulsars
        tot_dead_pulsars += dead_pulsars

    if current_pulsars == 0:
        break
    
# Now test the pulsar we are about to detect
# it must have the same array index as the loop number !!    
    if psr_array[0,5] == i:
# death line test
        if deathlinetest(psr_array[0,0],psr_array[0,1]):
            dead_index.append(j)
            dead_pulsars +=1
            death_liners +=1
            tot_dead_pulsars += 1
# luminosity test          
        elif luminositytest(psr_array[0,0],psr_array[0,1],psr_array[0,6]):
            dead_index.append(j)
            dead_pulsars +=1
            weaks +=1
            tot_dead_pulsars += 1
# Detection!            
        else:
            observed_pulsars[i] = psr_array[0,:]
            detected += 1
# Top one has either been observed or executed so delete it from the pulsar array
        psr_array = np.delete(psr_array,0,0)
        current_pulsars -= 1
# END OF MAIN LOOP
print "Birthrate (yr): ", birthrate, "stepsize: ", stepsize," npsrs: ", npsrs, " Lmin: ", Edot_highest
print "Dead info: beam: ", not_beaming," death-liners: ", death_liners, "too weak: ", weaks

# observed_pulsars array was same size as original psr_array, but is
# only populated with detections, so remove blank rows
dropped_index = []
for i in range(npsrs):
    if observed_pulsars[i,0] == 0:
        dropped_index.append(i)
    else:
        observed_pulsars[i,3] = edot(observed_pulsars[i,0],observed_pulsars[i,1])
observed_pulsars = np.delete(observed_pulsars, dropped_index, 0)

# for detected ones, overwrite alpha and zeta with edot and age
# write to output file
observed_pulsars[:,4] = age(observed_pulsars[:,0],observed_pulsars[:,1])
np.savetxt('simulated_ppdot.txt', observed_pulsars)

# plot
xobs = np.log10(observed_pulsars[:,0])
yobs = np.log10(observed_pulsars[:,1])
xyobs = np.vstack([xobs,yobs])
zobs = gaussian_kde(xyobs)(xyobs)
#fig, ax = plt.subplots()
ax.scatter(xobs, yobs, c=zobs, s=10, edgecolor='')
plt.show()
